# Generated by Django 2.2.27 on 2022-03-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='golfers',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='is_before',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='to_date',
        ),
    ]
