# Generated by Django 2.2.27 on 2022-03-04 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20220304_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={},
        ),
        migrations.AlterModelManagers(
            name='wish',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='password',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='username',
        ),
        migrations.AddField(
            model_name='wish',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='wish',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='wish',
            name='golfers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of Golfers'),
        ),
        migrations.AddField(
            model_name='wish',
            name='is_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='to_date',
            field=models.DateField(default=False, verbose_name='To'),
        ),
    ]
