# Generated by Django 2.2.27 on 2022-03-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20220304_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
