# Generated by Django 2.2.27 on 2022-03-08 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Created')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Golf course Location')),
                ('tee_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time')),
                ('no_of_selected_players', models.IntegerField(default=0, verbose_name='Number of selected players')),
                ('no_of_slots_available', models.IntegerField(default=0, verbose_name='All slots available for selected parameters')),
                ('no_of_max_players', models.IntegerField(default=0, verbose_name='Number of maximum players for opened slot')),
                ('website_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website Link')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Created')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Location')),
                ('golfers', models.IntegerField(default=0, verbose_name='Number of Golfers')),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('to_date', models.DateTimeField(default=False, verbose_name='To Date')),
                ('is_before_selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Created')),
                ('is_read', models.BooleanField(default=False)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Wish')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
