# Generated by Django 2.2.27 on 2022-03-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
