# Generated by Django 2.2.27 on 2022-03-04 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('golfers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of Golfers')),
                ('from_date', models.DateField(default=django.utils.timezone.now, verbose_name='From')),
                ('to_date', models.DateField(default=False, verbose_name='To')),
                ('is_before', models.BooleanField(default=False)),
            ],
        ),
    ]
