# Generated by Django 2.2.27 on 2022-03-06 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notification_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Golf course Location')),
                ('date_time', models.DateField(default=django.utils.timezone.now, verbose_name='Date and time')),
                ('no_of_selected_players', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of selected players')),
                ('no_of_slots_available', models.CharField(blank=True, max_length=255, null=True, verbose_name='All slots available for selected parameters')),
                ('no_of_max_players', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of maximum players for opened slot')),
                ('website_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website Link')),
            ],
        ),
    ]
