# Generated by Django 2.2.27 on 2022-03-06 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220306_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tee_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Notification Created Date Time'),
        ),
    ]
