# Generated by Django 2.2.27 on 2022-03-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220306_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no_of_max_players',
            field=models.IntegerField(default=0, verbose_name='Number of maximum players for opened slot'),
        ),
        migrations.AlterField(
            model_name='course',
            name='no_of_selected_players',
            field=models.IntegerField(default=0, verbose_name='Number of selected players'),
        ),
        migrations.AlterField(
            model_name='course',
            name='no_of_slots_available',
            field=models.IntegerField(default=0, verbose_name='All slots available for selected parameters'),
        ),
    ]
