# Generated by Django 2.2.27 on 2022-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220315_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_flaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
