# Generated by Django 2.2.27 on 2022-03-04 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220304_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 20, 21, 55, 995381), verbose_name='Date of birth'),
        ),
    ]
