# Generated by Django 2.2.27 on 2022-03-04 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220304_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 20, 24, 37, 152791), verbose_name='Date of birth'),
        ),
    ]
